/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;

import org.example.Controls.EventState;

import com.github.kwhat.jnativehook.GlobalScreen;
import com.github.kwhat.jnativehook.NativeHookException;
import com.github.kwhat.jnativehook.keyboard.NativeKeyEvent;
import com.github.kwhat.jnativehook.keyboard.NativeKeyListener;

public class App implements NativeKeyListener {
	public static EventState currentEventState = EventState.LOGIN; // Default state
	public static Login login = new Login();
	public static Home home = new Home();



    public static void main(String[] args) {
		Queries.GetAllBooks();//TODO: remove this line after testing connection to database is successful 
		
        try {
			GlobalScreen.registerNativeHook();
		}
		catch (NativeHookException ex) {
			System.err.println("There was a problem registering the native hook.");
			System.err.println(ex.getMessage());

			System.exit(1);
		}
		//==================== Login ================================
		GlobalScreen.addNativeKeyListener(new App());
		login.PrintLoginUI();
		
		
    }

	public void nativeKeyPressed(NativeKeyEvent e) {
		switch (currentEventState) {
			case LOGIN:
				login.LoginNativeKeyPressed(e);
				break;
			case HOME:
				home.HomeNativeKeyPressed(e);
				break;
			default:
				break;
		}
	}

	public void nativeKeyTyped(NativeKeyEvent e) {
		switch (currentEventState) {
			case LOGIN:
				login.LoginnativeKeyTyped(e);
				break;
			//walang home kasi walang key typed sa home
			default:
				break;
		}
	}

	
}
